[2016-11-27 01:34:38] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:34:38] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) PRAGMA foreign_keys; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) PRAGMA foreign_keys = 0; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends.schema:103] CREATE TABLE "catalogo_repuesto" ("id" char(32) NOT NULL PRIMARY KEY, "nombre" varchar(60) NULL, "codigo" varchar(60) NULL, "descripcion" varchar(60) NULL); (params None)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) CREATE TABLE "catalogo_repuesto" ("id" char(32) NOT NULL PRIMARY KEY, "nombre" varchar(60) NULL, "codigo" varchar(60) NULL, "descripcion" varchar(60) NULL); args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) PRAGMA foreign_keys = 0; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) INSERT INTO "django_migrations" ("app", "name", "applied") VALUES ('catalogo', '0006_repuesto', '2016-11-27 07:34:52.182989'); args=['catalogo', '0006_repuesto', '2016-11-27 07:34:52.182989']
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'logentry' AND "django_content_type"."app_label" = 'admin'); args=('logentry', 'admin')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'permission' AND "django_content_type"."app_label" = 'auth'); args=('permission', 'auth')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'group' AND "django_content_type"."app_label" = 'auth'); args=('group', 'auth')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'contenttype' AND "django_content_type"."app_label" = 'contenttypes'); args=('contenttype', 'contenttypes')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(4,)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'session' AND "django_content_type"."app_label" = 'sessions'); args=('session', 'sessions')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'corsmodel' AND "django_content_type"."app_label" = 'corsheaders'); args=('corsmodel', 'corsheaders')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'corsheaders'; args=('corsheaders',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'grant' AND "django_content_type"."app_label" = 'oauth2_provider'); args=('grant', 'oauth2_provider')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'refreshtoken' AND "django_content_type"."app_label" = 'oauth2_provider'); args=('refreshtoken', 'oauth2_provider')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'accesstoken' AND "django_content_type"."app_label" = 'oauth2_provider'); args=('accesstoken', 'oauth2_provider')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'application' AND "django_content_type"."app_label" = 'oauth2_provider'); args=('application', 'oauth2_provider')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.001) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8, 9, 10, 7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8, 9, 10, 7)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'oauth2_provider'; args=('oauth2_provider',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'userhierarchypermission' AND "django_content_type"."app_label" = 'auths'); args=('userhierarchypermission', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'hierarchytype' AND "django_content_type"."app_label" = 'auths'); args=('hierarchytype', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'menu' AND "django_content_type"."app_label" = 'auths'); args=('menu', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'person' AND "django_content_type"."app_label" = 'auths'); args=('person', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'hierarchy' AND "django_content_type"."app_label" = 'auths'); args=('hierarchy', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'user' AND "django_content_type"."app_label" = 'auths'); args=('user', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'userhierarchygroup' AND "django_content_type"."app_label" = 'auths'); args=('userhierarchygroup', 'auths')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (11, 12, 13, 14, 15, 16, 17) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(11, 12, 13, 14, 15, 16, 17)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auths'; args=('auths',)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'libro' AND "django_content_type"."app_label" = 'catalogo'); args=('libro', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'cliente' AND "django_content_type"."app_label" = 'catalogo'); args=('cliente', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'categoria' AND "django_content_type"."app_label" = 'catalogo'); args=('categoria', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'autor' AND "django_content_type"."app_label" = 'catalogo'); args=('autor', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'ejemplar' AND "django_content_type"."app_label" = 'catalogo'); args=('ejemplar', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'moto' AND "django_content_type"."app_label" = 'catalogo'); args=('moto', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'motor' AND "django_content_type"."app_label" = 'catalogo'); args=('motor', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.016) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'repuesto' AND "django_content_type"."app_label" = 'catalogo'); args=('repuesto', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."model" = 'repuesto' AND "django_content_type"."app_label" = 'catalogo'); args=('repuesto', 'catalogo')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) INSERT INTO "django_content_type" ("app_label", "model") VALUES ('catalogo', 'repuesto'); args=['catalogo', 'repuesto']
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (18, 19, 20, 21, 22, 23, 24, 25) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(18, 19, 20, 21, 22, 23, 24, 25)
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) INSERT INTO "auth_permission" ("name", "content_type_id", "codename") SELECT 'Can add Repuesto', 25, 'add_repuesto' UNION ALL SELECT 'Can change Repuesto', 25, 'change_repuesto' UNION ALL SELECT 'Can delete Repuesto', 25, 'delete_repuesto'; args=('Can add Repuesto', 25, 'add_repuesto', 'Can change Repuesto', 25, 'change_repuesto', 'Can delete Repuesto', 25, 'delete_repuesto')
[2016-11-27 01:34:52] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'catalogo'; args=('catalogo',)
[2016-11-27 01:35:20] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:35:20] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:38:41] INFO [django.server:131] "OPTIONS /api/auths/localuserinfo/ HTTP/1.1" 200 0
[2016-11-27 01:38:41] INFO [django.server:131] "OPTIONS /api/auths/usermenu/ HTTP/1.1" 200 0
[2016-11-27 01:38:41] INFO [django.server:131] "OPTIONS /api/catalogo/motor/ HTTP/1.1" 200 0
[2016-11-27 01:38:41] DEBUG [django.db.backends:90] (0.007) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'YfovShi6T2UiyT3xYQxhuPl1ryKBOo'; args=('YfovShi6T2UiyT3xYQxhuPl1ryKBOo',)
[2016-11-27 01:38:41] DEBUG [django.db.backends:90] (0.006) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'YfovShi6T2UiyT3xYQxhuPl1ryKBOo'; args=('YfovShi6T2UiyT3xYQxhuPl1ryKBOo',)
[2016-11-27 01:38:41] WARNING [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 401 58
[2016-11-27 01:38:41] WARNING [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 401 58
[2016-11-27 01:38:41] DEBUG [django.db.backends:90] (0.004) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = 'YfovShi6T2UiyT3xYQxhuPl1ryKBOo'; args=('YfovShi6T2UiyT3xYQxhuPl1ryKBOo',)
[2016-11-27 01:38:41] DEBUG [django.db.backends:90] (0.001) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:38:41] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:38:42] DEBUG [django.db.backends:90] (0.002) SELECT "auths_menu"."router_json" FROM "auths_menu" ORDER BY "auths_menu"."pos" ASC; args=()
[2016-11-27 01:38:42] INFO [django.server:131] "GET /api/auths/routers/ HTTP/1.1" 200 2
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\vemo_service\\\\vemo_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': '', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\vemo_service\\\\vemo_service_apps\\\\catalogo_api\\\\urls.py'> (None:None) ^api/catalogo/>"
[2016-11-27 01:39:21] WARNING [django.request:152] Not Found: /
[2016-11-27 01:39:21] WARNING [django.server:131] "GET / HTTP/1.1" 404 2455
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in '<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>'
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\django\\\\contrib\\\\admindocs\\\\urls.py'> (None:None) ^admin/doc/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'rest_framework.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\rest_framework\\\\urls.py'> (rest_framework:rest_framework) ^api-auth/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\ve_vemo\\\\lib\\\\site-packages\\\\oauth2_provider\\\\urls.py'> (None:oauth2_provider) ^o/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\vemo_service\\\\vemo_service_apps\\\\auths_api\\\\urls.py'> (None:None) ^api/auths/>"
[2016-11-27 01:39:21] DEBUG [django.template:929] Exception while resolving variable 'name' in template 'unknown'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\exception.py", line 39, in inner
    response = get_response(request)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\core\handlers\base.py", line 172, in _get_response
    resolver_match = resolver.resolve(request.path_info)
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\urls\resolvers.py", line 300, in resolve
    raise Resolver404({'tried': tried, 'path': new_path})
django.urls.exceptions.Resolver404: {'path': 'favicon.ico', 'tried': [[<RegexURLResolver <RegexURLPattern list> (admin:admin) ^admin/>], [<RegexURLResolver <module 'django.contrib.admindocs.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\django\\contrib\\admindocs\\urls.py'> (None:None) ^admin/doc/>], [<RegexURLResolver <module 'rest_framework.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\rest_framework\\urls.py'> (rest_framework:rest_framework) ^api-auth/>], [<RegexURLResolver <module 'oauth2_provider.urls' from 'E:\\LP2-PROYECT\\vemo\\ve_vemo\\lib\\site-packages\\oauth2_provider\\urls.py'> (None:oauth2_provider) ^o/>], [<RegexURLResolver <module 'vemo_service_apps.auths_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\auths_api\\urls.py'> (None:None) ^api/auths/>], [<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\LP2-PROYECT\\vemo\\vemo_service\\vemo_service_apps\\catalogo_api\\urls.py'> (None:None) ^api/catalogo/>]]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
TypeError: 'RegexURLResolver' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 893, in _resolve_lookup
    current = getattr(current, bit)
AttributeError: 'RegexURLResolver' object has no attribute 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [name] in "<RegexURLResolver <module 'vemo_service_apps.catalogo_api.urls' from 'E:\\\\LP2-PROYECT\\\\vemo\\\\vemo_service\\\\vemo_service_apps\\\\catalogo_api\\\\urls.py'> (None:None) ^api/catalogo/>"
[2016-11-27 01:39:21] WARNING [django.request:152] Not Found: /favicon.ico
[2016-11-27 01:39:21] WARNING [django.server:131] "GET /favicon.ico HTTP/1.1" 404 2488
[2016-11-27 01:39:38] INFO [django.server:131] "GET /admin HTTP/1.1" 301 0
[2016-11-27 01:39:38] INFO [django.server:131] "GET /admin/ HTTP/1.1" 302 0
[2016-11-27 01:39:38] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'False': False, 'True': True, 'None': None}, {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0078AC30>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00BA7730>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40}, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0078AB90>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x04320F60>>}, {}, {'LANGUAGE_BIDI': False, 'next': '/admin/', 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035ED9F0>, 'has_permission': False, 'site_name': '127.0.0.1:9000', 'site': <django.contrib.sites.requests.RequestSite object at 0x00B3F930>, 'site_url': '/', 'app_path': '/admin/login/?next=/admin/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDA50>, 'title': 'Log in', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'username': '', 'available_apps': []}]"
[2016-11-27 01:39:38] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/login.html'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'False': False, 'True': True, 'None': None}, {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x0078AC30>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00BA7730>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40}, 'request': <WSGIRequest: GET '/admin/login/?next=/admin/'>, 'user': <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x0078AB90>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x04320F60>>}, {}, {'LANGUAGE_BIDI': False, 'next': '/admin/', 'LANGUAGE_CODE': 'en-us', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035ED9F0>, 'has_permission': False, 'site_name': '127.0.0.1:9000', 'site': <django.contrib.sites.requests.RequestSite object at 0x00B3F930>, 'site_url': '/', 'app_path': '/admin/login/?next=/admin/', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDA50>, 'title': 'Log in', 'form': <AdminAuthenticationForm bound=False, valid=Unknown, fields=(username;password)>, 'username': '', 'available_apps': []}]"
[2016-11-27 01:39:38] INFO [django.server:131] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1658
[2016-11-27 01:39:38] INFO [django.server:131] "GET /static/admin/css/base.css HTTP/1.1" 200 15937
[2016-11-27 01:39:38] INFO [django.server:131] "GET /static/admin/css/login.css HTTP/1.1" 200 1203
[2016-11-27 01:39:38] INFO [django.server:131] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[2016-11-27 01:39:38] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 80304
[2016-11-27 01:39:38] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 81348
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.002) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."username" = 'admin'; args=('admin',)
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'o5coaydikg2j2ss2jsebcm2odiuyjmdx' LIMIT 1; args=('o5coaydikg2j2ss2jsebcm2odiuyjmdx',)
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'o5coaydikg2j2ss2jsebcm2odiuyjmdx', 'NWY5ZmU0MmU5OWVmZTEzNGMwN2ZjZGIwNmE4ODhjMjg1MWIyMjU3ODp7fQ==', '2016-12-11 07:39:50.064568'; args=('o5coaydikg2j2ss2jsebcm2odiuyjmdx', 'NWY5ZmU0MmU5OWVmZTEzNGMwN2ZjZGIwNmE4ODhjMjg1MWIyMjU3ODp7fQ==', '2016-12-11 07:39:50.064568')
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.001) UPDATE "auths_user" SET "last_login" = '2016-11-27 07:39:50.164498' WHERE "auths_user"."id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('2016-11-27 07:39:50.164498', 'f008d68e00524d18aa9ed8ca28530969')
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.002) UPDATE "django_session" SET "session_data" = 'ZGRlYzMxNWJkMjRhMWU5NjM4MDkwMmQ5MTU1ZDU3YzUxZjdiZGQ3MDp7Il9hdXRoX3VzZXJfaWQiOiJmMDA4ZDY4ZS0wMDUyLTRkMTgtYWE5ZS1kOGNhMjg1MzA5NjkiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImVmN2RiMmM1Mzg2ZDRkMGMxOTZmYTMwMTZhMDFhZTYyMGMxYWExOTAifQ==', "expire_date" = '2016-12-11 07:39:50.260910' WHERE "django_session"."session_key" = 'o5coaydikg2j2ss2jsebcm2odiuyjmdx'; args=('ZGRlYzMxNWJkMjRhMWU5NjM4MDkwMmQ5MTU1ZDU3YzUxZjdiZGQ3MDp7Il9hdXRoX3VzZXJfaWQiOiJmMDA4ZDY4ZS0wMDUyLTRkMTgtYWE5ZS1kOGNhMjg1MzA5NjkiLCJfYXV0aF91c2VyX2JhY2tlbmQiOiJkamFuZ28uY29udHJpYi5hdXRoLmJhY2tlbmRzLk1vZGVsQmFja2VuZCIsIl9hdXRoX3VzZXJfaGFzaCI6ImVmN2RiMmM1Mzg2ZDRkMGMxOTZmYTMwMTZhMDFhZTYyMGMxYWExOTAifQ==', '2016-12-11 07:39:50.260910', 'o5coaydikg2j2ss2jsebcm2odiuyjmdx')
[2016-11-27 01:39:50] INFO [django.server:131] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.005) SELECT "django_session"."session_key", "django_session"."session_data", "django_session"."expire_date" FROM "django_session" WHERE ("django_session"."session_key" = 'o5coaydikg2j2ss2jsebcm2odiuyjmdx' AND "django_session"."expire_date" > '2016-11-27 07:39:50.383378'); args=('o5coaydikg2j2ss2jsebcm2odiuyjmdx', '2016-11-27 07:39:50.383378')
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:39:50] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'False': False, 'True': True, 'None': None}, {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00BB31F0>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00BADCB0>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40}, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00BCF858>>}, {}, {'LANGUAGE_BIDI': False, 'app_list': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606630>, 'models': [{'object_name': 'Group', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3650>, 'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Permission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53DF0>, 'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True}, {'name': 'Auths', 'models': [{'object_name': 'HierarchyType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53810>, 'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Hierarchy', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B536B0>, 'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Menu', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3690>, 'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Person', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3510>, 'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyGroup', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3710>, 'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyPermission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB35B0>, 'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'User', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B537F0>, 'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True}, {'name': 'Catalogo', 'models': [{'object_name': 'Autor', 'name': 'Autores', 'add_url': '/admin/catalogo/autor/add/', 'admin_url': '/admin/catalogo/autor/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Categoria', 'name': 'Categorias', 'add_url': '/admin/catalogo/categoria/add/', 'admin_url': '/admin/catalogo/categoria/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Libro', 'name': 'Libros', 'add_url': '/admin/catalogo/libro/add/', 'admin_url': '/admin/catalogo/libro/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'catalogo', 'app_url': '/admin/catalogo/', 'has_module_perms': True}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606410>, 'models': [{'object_name': 'ContentType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3630>, 'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True}, {'name': 'Django OAuth Toolkit', 'models': [{'object_name': 'AccessToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB35F0>, 'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Application', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3830>, 'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Grant', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3770>, 'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'RefreshToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB36F0>, 'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True}], 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDA50>, 'site_url': '/', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035ED9F0>, 'has_permission': True, 'available_apps': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606630>, 'models': [{'object_name': 'Group', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53630>, 'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Permission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53F50>, 'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True}, {'name': 'Auths', 'models': [{'object_name': 'HierarchyType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B532B0>, 'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Hierarchy', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53A30>, 'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Menu', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B535F0>, 'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Person', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53B50>, 'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyGroup', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53BD0>, 'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyPermission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53D50>, 'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'User', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53610>, 'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True}, {'name': 'Catalogo', 'models': [{'object_name': 'Autor', 'name': 'Autores', 'add_url': '/admin/catalogo/autor/add/', 'admin_url': '/admin/catalogo/autor/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Categoria', 'name': 'Categorias', 'add_url': '/admin/catalogo/categoria/add/', 'admin_url': '/admin/catalogo/categoria/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Libro', 'name': 'Libros', 'add_url': '/admin/catalogo/libro/add/', 'admin_url': '/admin/catalogo/libro/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'catalogo', 'app_url': '/admin/catalogo/', 'has_module_perms': True}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606410>, 'models': [{'object_name': 'ContentType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53250>, 'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True}, {'name': 'Django OAuth Toolkit', 'models': [{'object_name': 'AccessToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53C10>, 'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Application', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53FD0>, 'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Grant', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53790>, 'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'RefreshToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53410>, 'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDAB0>}]"
[2016-11-27 01:39:50] DEBUG [django.template:929] Exception while resolving variable 'is_popup' in template 'admin/index.html'.
Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = current[bit]
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\context.py", line 75, in __getitem__
    raise KeyError(key)
KeyError: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 891, in _resolve_lookup
    if isinstance(current, BaseContext) and getattr(type(current), bit):
AttributeError: type object 'RequestContext' has no attribute 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 900, in _resolve_lookup
    current = current[int(bit)]
ValueError: invalid literal for int() with base 10: 'is_popup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\LP2-PROYECT\vemo\ve_vemo\lib\site-packages\django\template\base.py", line 907, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [is_popup] in "[{'False': False, 'True': True, 'None': None}, {'messages': <django.contrib.messages.storage.fallback.FallbackStorage object at 0x00BB31F0>, 'perms': <django.contrib.auth.context_processors.PermWrapper object at 0x00BADCB0>, 'DEFAULT_MESSAGE_LEVELS': {'WARNING': 30, 'DEBUG': 10, 'INFO': 20, 'SUCCESS': 25, 'ERROR': 40}, 'request': <WSGIRequest: GET '/admin/'>, 'user': <SimpleLazyObject: <User: admin>>, 'csrf_token': <SimpleLazyObject: <function csrf.<locals>._get_val at 0x00BCF858>>}, {}, {'LANGUAGE_BIDI': False, 'app_list': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606630>, 'models': [{'object_name': 'Group', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3650>, 'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Permission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53DF0>, 'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True}, {'name': 'Auths', 'models': [{'object_name': 'HierarchyType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53810>, 'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Hierarchy', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B536B0>, 'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Menu', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3690>, 'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Person', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3510>, 'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyGroup', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3710>, 'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyPermission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB35B0>, 'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'User', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B537F0>, 'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True}, {'name': 'Catalogo', 'models': [{'object_name': 'Autor', 'name': 'Autores', 'add_url': '/admin/catalogo/autor/add/', 'admin_url': '/admin/catalogo/autor/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Categoria', 'name': 'Categorias', 'add_url': '/admin/catalogo/categoria/add/', 'admin_url': '/admin/catalogo/categoria/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Libro', 'name': 'Libros', 'add_url': '/admin/catalogo/libro/add/', 'admin_url': '/admin/catalogo/libro/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'catalogo', 'app_url': '/admin/catalogo/', 'has_module_perms': True}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606410>, 'models': [{'object_name': 'ContentType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3630>, 'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True}, {'name': 'Django OAuth Toolkit', 'models': [{'object_name': 'AccessToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB35F0>, 'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Application', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3830>, 'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Grant', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB3770>, 'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'RefreshToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00BB36F0>, 'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True}], 'LANGUAGE_CODE': 'en-us', 'site_header': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDA50>, 'site_url': '/', 'site_title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035ED9F0>, 'has_permission': True, 'available_apps': [{'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606630>, 'models': [{'object_name': 'Group', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53630>, 'add_url': '/admin/auth/group/add/', 'admin_url': '/admin/auth/group/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Permission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53F50>, 'add_url': '/admin/auth/permission/add/', 'admin_url': '/admin/auth/permission/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auth', 'app_url': '/admin/auth/', 'has_module_perms': True}, {'name': 'Auths', 'models': [{'object_name': 'HierarchyType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B532B0>, 'add_url': '/admin/auths/hierarchytype/add/', 'admin_url': '/admin/auths/hierarchytype/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Hierarchy', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53A30>, 'add_url': '/admin/auths/hierarchy/add/', 'admin_url': '/admin/auths/hierarchy/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Menu', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B535F0>, 'add_url': '/admin/auths/menu/add/', 'admin_url': '/admin/auths/menu/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Person', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53B50>, 'add_url': '/admin/auths/person/add/', 'admin_url': '/admin/auths/person/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyGroup', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53BD0>, 'add_url': '/admin/auths/userhierarchygroup/add/', 'admin_url': '/admin/auths/userhierarchygroup/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'UserHierarchyPermission', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53D50>, 'add_url': '/admin/auths/userhierarchypermission/add/', 'admin_url': '/admin/auths/userhierarchypermission/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'User', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53610>, 'add_url': '/admin/auths/user/add/', 'admin_url': '/admin/auths/user/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'auths', 'app_url': '/admin/auths/', 'has_module_perms': True}, {'name': 'Catalogo', 'models': [{'object_name': 'Autor', 'name': 'Autores', 'add_url': '/admin/catalogo/autor/add/', 'admin_url': '/admin/catalogo/autor/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Categoria', 'name': 'Categorias', 'add_url': '/admin/catalogo/categoria/add/', 'admin_url': '/admin/catalogo/categoria/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Libro', 'name': 'Libros', 'add_url': '/admin/catalogo/libro/add/', 'admin_url': '/admin/catalogo/libro/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'catalogo', 'app_url': '/admin/catalogo/', 'has_module_perms': True}, {'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x03606410>, 'models': [{'object_name': 'ContentType', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53250>, 'add_url': '/admin/contenttypes/contenttype/add/', 'admin_url': '/admin/contenttypes/contenttype/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'contenttypes', 'app_url': '/admin/contenttypes/', 'has_module_perms': True}, {'name': 'Django OAuth Toolkit', 'models': [{'object_name': 'AccessToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53C10>, 'add_url': '/admin/oauth2_provider/accesstoken/add/', 'admin_url': '/admin/oauth2_provider/accesstoken/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Application', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53FD0>, 'add_url': '/admin/oauth2_provider/application/add/', 'admin_url': '/admin/oauth2_provider/application/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'Grant', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53790>, 'add_url': '/admin/oauth2_provider/grant/add/', 'admin_url': '/admin/oauth2_provider/grant/', 'perms': {'change': True, 'add': True, 'delete': True}}, {'object_name': 'RefreshToken', 'name': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x00B53410>, 'add_url': '/admin/oauth2_provider/refreshtoken/add/', 'admin_url': '/admin/oauth2_provider/refreshtoken/', 'perms': {'change': True, 'add': True, 'delete': True}}], 'app_label': 'oauth2_provider', 'app_url': '/admin/oauth2_provider/', 'has_module_perms': True}], 'title': <django.utils.functional.lazy.<locals>.__proxy__ object at 0x035EDAB0>}]"
[2016-11-27 01:39:50] DEBUG [django.db.backends:90] (0.000) SELECT "django_admin_log"."id", "django_admin_log"."action_time", "django_admin_log"."user_id", "django_admin_log"."content_type_id", "django_admin_log"."object_id", "django_admin_log"."object_repr", "django_admin_log"."action_flag", "django_admin_log"."change_message", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_admin_log" INNER JOIN "auths_user" ON ("django_admin_log"."user_id" = "auths_user"."id") LEFT OUTER JOIN "django_content_type" ON ("django_admin_log"."content_type_id" = "django_content_type"."id") WHERE "django_admin_log"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_admin_log"."action_time" DESC LIMIT 10; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:39:50] INFO [django.server:131] "GET /admin/ HTTP/1.1" 200 10333
[2016-11-27 01:39:50] INFO [django.server:131] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 434
[2016-11-27 01:39:50] INFO [django.server:131] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[2016-11-27 01:39:50] INFO [django.server:131] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[2016-11-27 01:39:50] INFO [django.server:131] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 82564
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_application" WHERE "oauth2_provider_application"."client_id" = 'UMsRRWv7OTz0O26Z7OjRE7NvzxYWtNBGVDXGs4d4'; args=('UMsRRWv7OTz0O26Z7OjRE7NvzxYWtNBGVDXGs4d4',)
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.000) SELECT "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by" FROM "auths_user" WHERE "auths_user"."username" = 'admin'; args=('admin',)
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.001) INSERT INTO "oauth2_provider_accesstoken" ("user_id", "token", "application_id", "expires", "scope") VALUES ('f008d68e00524d18aa9ed8ca28530969', '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0', 1, '2016-11-27 17:40:08.431853', 'write read'); args=['f008d68e00524d18aa9ed8ca28530969', '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0', 1, '2016-11-27 17:40:08.431853', 'write read']
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:40:08] DEBUG [django.db.backends:90] (0.001) INSERT INTO "oauth2_provider_refreshtoken" ("user_id", "token", "application_id", "access_token_id") VALUES ('f008d68e00524d18aa9ed8ca28530969', 'oTAGON4znfbZikiYrePwTltHpkQjee', 1, 5); args=['f008d68e00524d18aa9ed8ca28530969', 'oTAGON4znfbZikiYrePwTltHpkQjee', 1, 5]
[2016-11-27 01:40:08] INFO [django.server:131] "POST /o/token/ HTTP/1.1" 200 169
[2016-11-27 01:40:09] INFO [django.server:131] "OPTIONS /api/auths/usermenu/ HTTP/1.1" 200 0
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.003) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.008) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.001) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.001) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 01:40:09] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 496
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = '266vzuv2afblosj4dnc7oq8bet8j1bcu' LIMIT 1; args=('266vzuv2afblosj4dnc7oq8bet8j1bcu',)
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:40:09] DEBUG [django.db.backends:90] (0.068) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT '266vzuv2afblosj4dnc7oq8bet8j1bcu', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:40:39.120146'; args=('266vzuv2afblosj4dnc7oq8bet8j1bcu', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:40:39.120146')
[2016-11-27 01:40:09] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 01:40:21] INFO [django.server:131] "OPTIONS /api/catalogo/moto/ HTTP/1.1" 200 0
[2016-11-27 01:40:21] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:40:21] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_moto"."id", "catalogo_moto"."nombre", "catalogo_moto"."tipo", "catalogo_moto"."motor", "catalogo_moto"."descripcion" FROM "catalogo_moto"; args=()
[2016-11-27 01:40:21] INFO [django.server:131] "GET /api/catalogo/moto/ HTTP/1.1" 200 241
[2016-11-27 01:40:23] INFO [django.server:131] "OPTIONS /api/catalogo/motor/ HTTP/1.1" 200 0
[2016-11-27 01:40:23] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:40:23] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:40:23] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:42:01] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:42:01] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:43:01] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:43:01] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:43:05] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:43:05] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.006) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'rwumjilpu6cy9dxqp7huaq8zx5o2749b' LIMIT 1; args=('rwumjilpu6cy9dxqp7huaq8zx5o2749b',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.001) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.001) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'rwumjilpu6cy9dxqp7huaq8zx5o2749b', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:43:40.287896'; args=('rwumjilpu6cy9dxqp7huaq8zx5o2749b', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:43:40.287896')
[2016-11-27 01:43:10] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 496
[2016-11-27 01:43:10] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:10] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:43:10] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.004) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'f3vyy0l7too0of0sknlajv5r3o0bnzr3' LIMIT 1; args=('f3vyy0l7too0of0sknlajv5r3o0bnzr3',)
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.001) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:43:22] DEBUG [django.db.backends:90] (0.001) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'f3vyy0l7too0of0sknlajv5r3o0bnzr3', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:43:52.834868'; args=('f3vyy0l7too0of0sknlajv5r3o0bnzr3', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:43:52.834868')
[2016-11-27 01:43:22] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 496
[2016-11-27 01:43:22] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 01:43:23] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:43:23] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:43:23] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.000) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.008) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.001) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 01:44:48] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 496
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'tv6dqq5k5agjjcvri8r3u02rh89pwf6d' LIMIT 1; args=('tv6dqq5k5agjjcvri8r3u02rh89pwf6d',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.001) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'tv6dqq5k5agjjcvri8r3u02rh89pwf6d', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:45:18.574936'; args=('tv6dqq5k5agjjcvri8r3u02rh89pwf6d', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:45:18.574936')
[2016-11-27 01:44:48] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:44:48] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:44:48] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:46:16] DEBUG [django.db.backends:90] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:46:16] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'admin' AND "django_content_type"."model" = 'logentry'); args=('admin', 'logentry')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (1) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(1,)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'admin'; args=('admin',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'group'); args=('auth', 'group')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auth' AND "django_content_type"."model" = 'permission'); args=('auth', 'permission')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (2, 3) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(2, 3)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auth'; args=('auth',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'contenttypes' AND "django_content_type"."model" = 'contenttype'); args=('contenttypes', 'contenttype')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (4) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(4,)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'contenttypes'; args=('contenttypes',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'sessions' AND "django_content_type"."model" = 'session'); args=('sessions', 'session')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (5) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(5,)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'sessions'; args=('sessions',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'corsheaders' AND "django_content_type"."model" = 'corsmodel'); args=('corsheaders', 'corsmodel')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (6) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(6,)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'corsheaders'; args=('corsheaders',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'oauth2_provider' AND "django_content_type"."model" = 'application'); args=('oauth2_provider', 'application')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'oauth2_provider' AND "django_content_type"."model" = 'refreshtoken'); args=('oauth2_provider', 'refreshtoken')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'oauth2_provider' AND "django_content_type"."model" = 'accesstoken'); args=('oauth2_provider', 'accesstoken')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'oauth2_provider' AND "django_content_type"."model" = 'grant'); args=('oauth2_provider', 'grant')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (8, 9, 10, 7) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(8, 9, 10, 7)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'oauth2_provider'; args=('oauth2_provider',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'userhierarchypermission'); args=('auths', 'userhierarchypermission')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'hierarchytype'); args=('auths', 'hierarchytype')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'user'); args=('auths', 'user')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'hierarchy'); args=('auths', 'hierarchy')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'menu'); args=('auths', 'menu')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'userhierarchygroup'); args=('auths', 'userhierarchygroup')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'auths' AND "django_content_type"."model" = 'person'); args=('auths', 'person')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (11, 12, 13, 14, 15, 16, 17) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(11, 12, 13, 14, 15, 16, 17)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'auths'; args=('auths',)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'autor'); args=('catalogo', 'autor')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.001) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'motor'); args=('catalogo', 'motor')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'repuesto'); args=('catalogo', 'repuesto')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'libro'); args=('catalogo', 'libro')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'cliente'); args=('catalogo', 'cliente')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'moto'); args=('catalogo', 'moto')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'categoria'); args=('catalogo', 'categoria')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE ("django_content_type"."app_label" = 'catalogo' AND "django_content_type"."model" = 'ejemplar'); args=('catalogo', 'ejemplar')
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auth_permission"."content_type_id" IN (18, 19, 20, 21, 22, 23, 24, 25) ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=(18, 19, 20, 21, 22, 23, 24, 25)
[2016-11-27 01:46:21] DEBUG [django.db.backends:90] (0.000) SELECT "django_content_type"."id", "django_content_type"."app_label", "django_content_type"."model" FROM "django_content_type" WHERE "django_content_type"."app_label" = 'catalogo'; args=('catalogo',)
[2016-11-27 01:46:34] DEBUG [django.db.backends:90] (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[2016-11-27 01:46:34] DEBUG [django.db.backends:90] (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.002) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.003) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.000) SELECT "auths_menu"."id" FROM "auths_menu" WHERE ("auths_menu"."id" IS NOT NULL AND "auths_menu"."is_active" = 1 AND "auths_menu"."module" = 'BACKEND') ORDER BY "auths_menu"."pos" ASC; args=(True, 'BACKEND')
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.000) SELECT (1) AS "a" FROM "django_session" WHERE "django_session"."session_key" = 'x6xbr3hxtj4m08xdsauytvkzjhbudc5l' LIMIT 1; args=('x6xbr3hxtj4m08xdsauytvkzjhbudc5l',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.001) SELECT "auth_group"."id", "auth_group"."name" FROM "auth_group" INNER JOIN "auths_user_groups" ON ("auth_group"."id" = "auths_user_groups"."group_id") WHERE "auths_user_groups"."user_id" = 'f008d68e00524d18aa9ed8ca28530969'; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.000) SELECT "auth_permission"."id", "auth_permission"."name", "auth_permission"."content_type_id", "auth_permission"."codename" FROM "auth_permission" INNER JOIN "auths_user_user_permissions" ON ("auth_permission"."id" = "auths_user_user_permissions"."permission_id") INNER JOIN "django_content_type" ON ("auth_permission"."content_type_id" = "django_content_type"."id") WHERE "auths_user_user_permissions"."user_id" = 'f008d68e00524d18aa9ed8ca28530969' ORDER BY "django_content_type"."app_label" ASC, "django_content_type"."model" ASC, "auth_permission"."codename" ASC; args=('f008d68e00524d18aa9ed8ca28530969',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.001) INSERT INTO "django_session" ("session_key", "session_data", "expire_date") SELECT 'x6xbr3hxtj4m08xdsauytvkzjhbudc5l', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:48:08.674993'; args=('x6xbr3hxtj4m08xdsauytvkzjhbudc5l', 'NmE3M2Q3NmYwOTU3YjJmZDBjYmQxYTVjODc5MTExNzM3NjY1YzYzNzp7Il9zZXNzaW9uX2V4cGlyeSI6MzB9', '2016-11-27 07:48:08.674993')
[2016-11-27 01:47:38] INFO [django.server:131] "GET /api/auths/localuserinfo/ HTTP/1.1" 200 496
[2016-11-27 01:47:38] INFO [django.server:131] "GET /api/auths/usermenu/ HTTP/1.1" 200 11
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:47:38] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_motor"."id", "catalogo_motor"."serie", "catalogo_motor"."tipoMotor", "catalogo_motor"."marca", "catalogo_motor"."descripcion" FROM "catalogo_motor"; args=()
[2016-11-27 01:47:38] INFO [django.server:131] "GET /api/catalogo/motor/ HTTP/1.1" 200 361
[2016-11-27 01:47:44] INFO [django.server:131] "OPTIONS /api/catalogo/repuesto/ HTTP/1.1" 200 0
[2016-11-27 01:47:44] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:47:44] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_repuesto"."id", "catalogo_repuesto"."nombre", "catalogo_repuesto"."codigo", "catalogo_repuesto"."descripcion" FROM "catalogo_repuesto"; args=()
[2016-11-27 01:47:44] INFO [django.server:131] "GET /api/catalogo/repuesto/ HTTP/1.1" 200 2
[2016-11-27 01:48:50] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:48:50] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:48:50] DEBUG [django.db.backends:90] (0.047) INSERT INTO "catalogo_repuesto" ("id", "nombre", "codigo", "descripcion") SELECT 'c43add03caf6482c820608941de9c0cb', 'triste alegre', '6126212', 'para el motor'; args=('c43add03caf6482c820608941de9c0cb', 'triste alegre', '6126212', 'para el motor')
[2016-11-27 01:48:50] INFO [django.server:131] "POST /api/catalogo/repuesto/ HTTP/1.1" 201 119
[2016-11-27 01:48:50] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:48:50] DEBUG [django.db.backends:90] (0.000) SELECT "catalogo_repuesto"."id", "catalogo_repuesto"."nombre", "catalogo_repuesto"."codigo", "catalogo_repuesto"."descripcion" FROM "catalogo_repuesto"; args=()
[2016-11-27 01:48:50] INFO [django.server:131] "GET /api/catalogo/repuesto/ HTTP/1.1" 200 121
[2016-11-27 01:49:06] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:49:06] DEBUG [django.db.backends:90] (0.001) SELECT "catalogo_moto"."id", "catalogo_moto"."nombre", "catalogo_moto"."tipo", "catalogo_moto"."motor", "catalogo_moto"."descripcion" FROM "catalogo_moto"; args=()
[2016-11-27 01:49:06] INFO [django.server:131] "GET /api/catalogo/moto/ HTTP/1.1" 200 241
[2016-11-27 01:49:23] DEBUG [django.db.backends:90] (0.001) SELECT "oauth2_provider_accesstoken"."id", "oauth2_provider_accesstoken"."user_id", "oauth2_provider_accesstoken"."token", "oauth2_provider_accesstoken"."application_id", "oauth2_provider_accesstoken"."expires", "oauth2_provider_accesstoken"."scope", "auths_user"."password", "auths_user"."last_login", "auths_user"."is_superuser", "auths_user"."username", "auths_user"."first_name", "auths_user"."last_name", "auths_user"."email", "auths_user"."is_staff", "auths_user"."is_active", "auths_user"."date_joined", "auths_user"."id", "auths_user"."last_hierarchy_id", "auths_user"."last_module_id", "auths_user"."person_id", "auths_user"."updated_at", "auths_user"."registered_by", "oauth2_provider_application"."id", "oauth2_provider_application"."client_id", "oauth2_provider_application"."user_id", "oauth2_provider_application"."redirect_uris", "oauth2_provider_application"."client_type", "oauth2_provider_application"."authorization_grant_type", "oauth2_provider_application"."client_secret", "oauth2_provider_application"."name", "oauth2_provider_application"."skip_authorization" FROM "oauth2_provider_accesstoken" LEFT OUTER JOIN "auths_user" ON ("oauth2_provider_accesstoken"."user_id" = "auths_user"."id") INNER JOIN "oauth2_provider_application" ON ("oauth2_provider_accesstoken"."application_id" = "oauth2_provider_application"."id") WHERE "oauth2_provider_accesstoken"."token" = '5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0'; args=('5XCnmfF8PoKFNuBf6TgN4zGzyKj1k0',)
[2016-11-27 01:49:23] DEBUG [django.db.backends:90] (0.000) BEGIN; args=None
[2016-11-27 01:49:23] DEBUG [django.db.backends:90] (0.065) INSERT INTO "catalogo_moto" ("id", "nombre", "tipo", "motor", "descripcion") SELECT '0d4e58f4e41a4dfd9efeee915d232c8c', 'suzuki', 'pistera', '300', 'motocros'; args=('0d4e58f4e41a4dfd9efeee915d232c8c', 'suzuki', 'pistera', '300', 'motocros')
[2016-11-27 01:49:23] INFO [django.server:131] "POST /api/catalogo/moto/ HTTP/1.1" 201 119
